server:
#  ssl:
#    key-store: classpath:rds-combined-ca-bundle.pem
  port: '7070'
spring:
  application:
    name: processor
  data:
    mongodb:
      database: svm
      #      uri: mongodb://aktimetrix:aktimetrix@aktimetrix.cluster-cmxtn9dh3lty.ap-south-1.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      uri: mongodb+srv://admin:admin%40123@aruncluster.70orz.mongodb.net/?retryWrites=true&w=majority
  jackson:
    serialization:
      write-dates-as-timestamps: false
  #    default-property-inclusion: always, non_null, non_absent, non_default, non_empty
  kafka:
    properties:
      #      sasl:
      #        jaas:
      #          config: org.apache.kafka.common.security.plain.PlainLoginModule   required
      #            username='7I2IL2UTBVQG4MN7'   password='xdCW7HbRg0JEOOsSJMm/ljYy08JebRYTCrx9E2BfMv6XnFRw7GNTZIAE5B3uBbsA';
      #        mechanism: PLAIN
      session:
        timeout:
          ms: '45000'
      #      security:
      #        protocol: SASL_SSL
      bootstrap:
        #        servers: pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092
        servers: localhost:29092
  cloud:
    stream:
      function:
        bindings:
          processor-in-0: cargo-event-processor
        definition: processor
      bindings:
        cargo-event-processor:
          group: processor.cargo.group.0
          destination: cargo-event-topic
      source: process-instance;step-instance
      kafka:
        bindings:
          process-instance-out-0:
            producer:
              configuration:
                "[key.serializer]": org.apache.kafka.common.serialization.StringSerializer
          step-instance-out-0:
            producer:
              configuration:
                "[key.serializer]": org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    com.aktimetrix: DEBUG
