server:
  port: ${SERVER_PORT:2020}
spring:
  freemarker:
    template-loader-path: "classpath:/"
  application:
    name: planner
  data:
    mongodb:
      database: ${DATABASE_NAME:planner}
      uri: ${DATABASE_URI:}
  jackson:
    serialization:
      write-dates-as-timestamps: false
  kafka:
    properties:
      session:
        timeout:
          ms: '45000'
      bootstrap:
        servers: ${KAFKA_BOOTSTRAP_SERVERS:}
  cloud:
    function:
      definition: stepConsumer;processConsumer;measurementConsumer
    stream:
      function:
        bindings:
          stepConsumer-in-0: step
          processConsumer-in-0: process
          measurementConsumer-in-0: measurement
      bindings:
        step:
          destination: step-instance-out-0
          group: planner.step.group.0
        process:
          destination: process-instance-out-0
          group: planner.process.group.0
        measurement:
          destination: measurement-instance-out-0
          group: planner.measurement.group.0
      source: process-plan-instance
      kafka:
        bindings:
          process-plan-instance-out-0:
            producer:
              configuration:
                "[key.serializer]": org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG
    com.aktimetrix: DEBUG
    org.springframework.integration.sftp: TRACE
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG
    httpclient.wire: DEBUG

aktimetrix:
  consumer:
    plan:
      enabled: false
    process:
      enabled: false
    step:
      enabled: false
    measurement:
      enabled: true
tenant:
  code: "XX"
  airlinecode:  "XX"
ciq:
  airlineCode: "XX"
  cdmpIdentifier: "XX"
  cdmpType: C
  phase-number: 1
  message-version: 12
  email-id: ak.kandakatla@gmail.com
  timestamp-format: yyyy-MM-ddThh:mi:ss
  transfer-mode: ASCII
  temporary-file-suffix: ".tmp"
  single-or-multiple-indicator: S
  file-format: "${date}${sequenceNumber}_${singleOrMultiple}_${messageType}_${messageVersion}_${cdmpIdentifier}_${forwarderIdentifier}_${carrierCode}_${messageReference}"
  cdmpc:
    encore:
      reference-data:
        base-url: http://localhost:6060
        routes: /reference-data/encore/routes
      default-line-offsets:
        FWB: 365
        LAT: 360
        RCS: 120
        DEP: 60
        ARR: 60
        AWR: 0
        RCF: 240
        NFD: 240
        AWD: 240
        DLV: 4320
        RCF-T: 45
        TFD-T: 0
        ARR-T: 40
        RCT-T: 0
        DEP-T: 60
