server:
  port: ${SERVER_PORT:6060}
spring:
  application:
    name: meter
  data:
    mongodb:
      database: ${DATABASE_NAME:meter}
      uri: ${DATABASE_URI:}
  kafka:
    properties:
      session:
        timeout:
          ms: '45000'
      bootstrap:
        servers: ${KAFKA_BOOTSTRAP_SERVERS:}
  cloud:
    stream:
      function:
        bindings:
          measure-in-0: step-event-processor
        definition: measure
      bindings:
        step-event-processor:
          group: meter.step.group.0
          destination: step-instance-out-0
      source: measurement-instance
      kafka:
        bindings:
          measurement-instance-out-0:
            producer:
              configuration:
                "[key.serializer]": org.apache.kafka.common.serialization.StringSerializer
          step-event-processor:
            consumer:
              enableDlq: true
              dlqName: input-topic-dlq
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG
    com.aktimetrix.core: DEBUG


aktimetrix:
  consumer:
    process:
      enabled: true
    step:
      enabled: true
    measurement:
      enabled: true
  meter:
    process-code: DEFAULT
    process-type: DEFAULT

ciq:
  cdmpIdentifier: "XX"
  cdmpType: C
  phase-number: 1
  message-version: 12
  email-id: ak.kandakatla@gmail.com
  timestamp-format: yyyy-MM-ddThh:mi:ss
  transfer-mode: ASCII
  temporary-file-suffix: ".tmp"
  single-or-multiple-indicator: S
  file-format: "${date}${sequenceNumber}_${singleOrMultiple}_${messageType}_${messageVersion}_${cdmpIdentifier}_${forwarderIdentifier}_${carrierCode}_${messageReference}"
  cdmpc:
    encore:
      default-line-offsets:
        FWB: 365
        LAT: 360
        RCS: 120
        DEP: 60
        ARR: 60
        AWR: 0
        RCF: 240
        NFD: 240
        AWD: 240
        DLV: 4320
        RCF-T: 45
        TFD-T: 0
        ARR-T: 40
        RCT-T: 0
        DEP-T: 60